version: '3.9'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/dev/nginx/Dockerfile
    container_name: pva-nginx-mars
    ports:
      - '8080:80'
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/dev/php/Dockerfile
    container_name: pva-php-mars
    volumes:
      - './:/var/www/html'
    depends_on:
      - database

  database:
    image: postgres:${POSTGRES_VERSION}
    container_name: pva-db-mars
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - pva_db_data:/var/lib/postgresql/data:rw

volumes:
  pva_db_data:
