version: '3.9'

services:
  nginx:
    image: nginx:1.25
    container_name: pva-nginx
    ports:
      - '8080:80'
    volumes:
      - ./docker/prod/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build: docker/prod/php
    container_name: pva-php
    volumes:
      - './:/var/www/html'

  database:
    image: postgres:${POSTGRES_VERSION}
    container_name: pva-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - pva_db_data:/var/lib/postgresql/data:rw

volumes:
  pva_db_data: