controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: '/api'
api_login_check:
    path: /api/login
api_token_refresh:
    path: /api/login/refresh
